// tech: frameworks, api, semi-frameworks, stylers
const projects = [
  {
    title: "Spotify",
    src: "spotify.png",
    slug: "spotify",
    code: "spotify",
    color: "#FFF",
    tech: "NextJs, Spotify-Web-API-Node, Next-Auth, Recoil, Tailwind, Framer-Motion",
    href: "https://joshuaedo-spotify.vercel.app/",
    year: 2023,
    demo: "https://youtu.be/RDafUnvD090",
  },
  {
    title: "Netflix",
    src: "netflix.png",
    slug: "netflix",
    code: "netflix",
    color: "#EFE8D3",
    tech: "ReactJs, TMDB API, Redux, React-Router, Firebase, Lodash",
    href: "https://joshuaedo-binge.vercel.app/",
    year: 2023,
    demo: "https://youtu.be/krHx-I6npkM",
  },
  {
    title: "Google",
    src: "google.png",
    slug: "google",
    code: "google",
    color: "#706D63",
    tech: "NextJs, Google API, Recoil, Tailwind, Hero Icons",
    href: "https://joshuaedo-google.vercel.app/",
    year: 2023,
    demo: "https://youtu.be/qO7OML8_Pnk",
  },
  // {
  // title: 'Arese Sylvester',
  // src: "arese.png",
  // slug: "arese",
  // code: "https://github.com/omgitsarese/aresesylvester"
  // color: "#706D63",
  // href: 'https://www.aresesylvester.com/',
  // year: 2022,
  // demo: "https://drive.google.com/file/d/1DHGDV1PPAv0449WfFUwjy2BBQ3okfAQd/view?usp=drive_link",
  //},
  {
    title: "Apple",
    src: "apple.png",
    slug: "apple",
    code: "apple",
    color: "#FFF",
    tech: "NextJs, Tailwind, React-Responsive-Carousel, Framer-Motion",
    href: "https://apple-joshuaedo.vercel.app/",
    year: 2023,
    demo: "https://twitter.com/thegr8joshua/status/1670077556521926656",
  },
  {
    title: "Portfolio V3",
    src: "portfolio-v3.png",
    slug: "portfolio-v3",
    code: "portfolio-v3",
    color: "#8C8C8C",
    tech: "NextJs, JQuery, NodeMailer, Tailwind, React-Bootstrap, Framer-Motion",
    href: "https://joshuaedo-v3.vercel.app/",
    year: 2023,
    demo: null,
  },
  {
    title: "Blog",
    src: "blog.png",
    slug: "blog",
    code: "my-blog",
    color: "#8C8C8C",
    tech: "NextJs, GraphQL, Hygraph, OpenAI Model Playground",
    href: "https://joshuaedo-blog.vercel.app/",
    year: 2023,
    demo: null,
  },
  {
    title: "Cleander",
    src: "cleander.png",
    slug: "cleander",
    code: "cleander",
    color: "#FFF",
    tech: "HTML, CSS, Bootstrap, Font-Awesome",
    href: "https://thecleander.netlify.app/",
    year: 2022,
    demo: null,
  },
  {
    title: "joshua-GPT",
    src: "joshuaGPT.png",
    slug: "joshua-gpt",
    code: null,
    color: "#8C8C8C",
    tech: "NodeJs, ExpressJs, OpenAI API, Node-Telegram-Bot-API, Dotenv",
    href: "https://t.me/joshuaedo_bot",
    year: 2023,
    demo: "https://youtu.be/yuroCFONrTo",
  },
  {
    title: "Style Your Div",
    src: "style-your-div.png",
    slug: "style-your-div",
    code: "style-your-div",
    color: "#FFF",
    tech: "HTML, CSS",
    href: "https://style-your-div.netlify.app/",
    year: 2023,
    demo: "https://twitter.com/thegr8joshua/status/1627770957971456001",
  },
  {
    title: "Ryter",
    src: "ryter.png",
    slug: "ryter",
    code: "ryter",
    color: "#EFE8D3",
    tech: "HTML, Javascript, CSS, Font-Awesome",
    href: "https://ryter.netlify.app/",
    year: 2022,
    demo: null,
  },
  {
    title: "Business Card",
    src: "business-card.png",
    slug: "business-card",
    code: "business-card",
    color: "#8C8C8C",
    tech: "ReactJs, Font-Awesome",
    href: "https://joshuaedocard.netlify.app/",
    year: 2023,
    demo: null,
  },
  {
    title: "Drum Kit",
    src: "drum.png",
    slug: "drum",
    code: "Drum-Hero",
    color: "#EFE8D3",
    tech: "HTML, JavaScript, CSS",
    href: "https://josh-drum.netlify.app/",
    year: 2022,
    demo: null,
  },
  {
    title: "Dice Game",
    src: "dice.png",
    slug: "dice",
    code: "Dice-Game",
    color: "#706D63",
    tech: "HTML, JavaScript, CSS",
    href: "https://thesimpledicegame.netlify.app/",
    year: 2022,
    demo: null,
  },
  {
    title: "Portfolio V2",
    src: "portfolio-v2.png",
    slug: "portfolio-v2",
    code: "portfolio-V2",
    color: "#EFE8D3",
    tech: "HTML, CSS",
    href: "https://joshuaedo-v2.vercel.app/",
    year: 2022,
    demo: null,
  },
  {
    title: "Portfolio V1",
    src: "portfolio-v1.png",
    slug: "portfolio-v1",
    code: "portfolio-V1",
    color: "#706D63",
    tech: "HTML",
    href: "https://joshuaedo-v1.vercel.app/",
    year: 2022,
    demo: null,
  },
];

export { projects };

export async function getProjects(slug) {
  return new Promise((resolve) => {
    setTimeout(() => {
      if (slug) {
        const project = projects.filter((p) => p.slug === slug);
        resolve(project);
      } else {
        resolve(projects);
      }
    }, 1000);
  });
}
