// tech: languages, frameworks, api, semi-frameworks, stylers, animators
const allProjects = [
  {
    title: 'Shop Josh',
    src: 'shop',
    slug: 'shop-josh',
    code: 'shop',
    tech: 'Typescript, NextJs, ECE, React-Query, Tailwind, Framer-Motion, GSAP',
    href: 'https://shop.joshuaedo.com',
    year: 2024,
    demo: null,
    overview: "Live like Josh's alter ego, j@28.",
    description: null,
    documentation: 'https://github.com/joshuaedo/shop#readme',
    isDisplayed: true,
  },
  {
    title: 'Ecommerce Engine',
    src: 'ecommerce-engine',
    slug: 'ecommerce-engine',
    code: 'ecommerce-engine',
    tech: 'Typescript, Zod, NextJs, Next-Auth, Prisma, Tailwind',
    href: 'https://ece.joshuaedo.com/',
    year: 2024,
    demo: null,
    overview: 'Powering Online Stores.',
    description:
      'Ecommerce Engine provides all the tools you need to manage, optimize, and grow your online store.',
    documentation: 'https://github.com/joshuaedo/ecommerce-engine#readme',
    isDisplayed: true,
  },
  {
    title: 'Cakkie',
    src: 'cakkie',
    slug: 'cakkie',
    code: null,
    tech: 'Typescript, Zod, NextJs, React-Query, Recharts, Tailwind',
    href: null,
    year: 2024,
    demo: null,
    overview: 'Admin dashboard for Cakkie Foods Ltd.',
    description: null,
    documentation:
      'https://github.com/Cakkie-team/cakkie-admin-dashboard#readme',
    isDisplayed: true,
  },
  {
    title: 'Zuri Portfolio',
    src: 'zuri-portfolio',
    slug: 'zuri-portfolio',
    code: null,
    tech: 'Typescript, Zod, NextJs, React-Query, Recharts, Tailwind',
    href: 'https://zuriportfolio.vercel.app',
    year: 2023,
    demo: null,
    overview: 'Explore. Showcase. Sell. Connect.',
    description:
      'Explore a world of talents, create your personalized portfolio, and sell your digital products in your very own shop.',
    documentation: 'https://github.com/hngx-org/zuriportfolio-frontend#readme',
    isDisplayed: true,
  },
  {
    title: 'Sandra',
    src: 'sandra',
    slug: 'sandra',
    code: null,
    tech: 'Typescript, NextJs, Next-Auth, Hygraph, Sass, Tailwind, Framer-Motion, GSAP',
    href: 'https://sandraokpara.com',
    year: 2023,
    demo: null,
    overview: 'Writing on Earth.',
    description:
      "This blog is a canvas for Sandra Okpara's diverse range of interests.",
    documentation: 'https://github.com/sandraokpara/blog#readme',
    isDisplayed: true,
  },
  {
    title: 'Z',
    src: 'z',
    slug: 'z',
    code: null,
    tech: 'Typescript, NextJs, Prisma, Next-Auth, React-Query, Upload-Thing, Tailwind',
    href: 'https://z.joshuaedo.com',
    year: 2023,
    demo: null,
    overview: 'Join the conversation.',
    description:
      'A community-oriented social network inspired by Reddit and Twitter.',
    documentation: null,
    isDisplayed: true,
  },
  {
    title: 'Galleria',
    src: 'galleria',
    slug: 'galleria',
    code: 'galleria',
    tech: 'Typescript, NextJs, Pexels API, Next-Auth, React-Query, DND-Kit, Tailwind',
    href: 'https://galleria.joshuaedo.com',
    year: 2023,
    demo: null,
    overview:
      'An interactive stock image gallery with drag-and-drop functionality.',
    description:
      'Galleria is my version of the HNGX 2023 Frontend Stage 3 Task.',
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'Spotify',
    src: 'spotify',
    slug: 'spotify',
    code: 'spotify',
    tech: 'NextJs, Spotify API, Next-Auth, Recoil, Tailwind, Framer-Motion',
    href: 'https://joshuaedo-spotify.vercel.app/',
    year: 2023,
    demo: 'https://youtu.be/RDafUnvD090',
    overview:
      'A recreation of the Spotify web app UI with some conditional functionality.',
    description:
      'Apart from rendering songs and playlists, the app also acts as a remote control for other devices where you are logged into your Spotify Account.',
    documentation: 'https://github.com/joshuaedo/spotify#readme',
    isDisplayed: true,
  },
  {
    title: 'Prime',
    src: 'prime',
    slug: 'prime',
    code: 'amazon',
    tech: 'NextJs, Stripe, Firebase & Firestore, Redux, Tailwind',
    href: 'https://joshuaedo-prime.vercel.app/',
    year: 2023,
    demo: null,
    overview: 'An E-commerce app inspired by Amazon.com',
    description:
      'The Fake Store API was used to create an online store with full authentication and payment workflow.',
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'Blog',
    src: 'blog',
    slug: 'blog',
    code: 'my-blog',
    tech: 'NextJs, GraphQL, Hygraph, OpenAI Model Playground.',
    href: 'https://blog.joshuaedo.com/',
    year: 2023,
    demo: null,
    overview:
      'This app was built to gain experience in the utilization of GraphQL and Headless CMS.',
    description: 'Disclaimer: The articles on this website are AI-generated.',
    documentation: null,
    isDisplayed: true,
  },
  {
    title: 'Google',
    src: 'google',
    slug: 'google',
    code: 'google',
    tech: 'NextJs, Google API, Recoil, Tailwind, Hero Icons.',
    href: 'https://joshuaedo-google.vercel.app/',
    year: 2023,
    demo: 'https://youtu.be/qO7OML8_Pnk',
    overview: "It's basically google.com but not quite.",
    description:
      "Utilizing the open source Google API, I recreated Google Search. To the casual user it's not immediately differentiable from the real website.",
    documentation: 'https://github.com/joshuaedo/google/#readme',
    isDisplayed: false,
  },
  {
    title: 'Arese',
    src: 'arese',
    slug: 'arese',
    code: null,
    tech: 'JavaScript, HTML, CSS, Bootstrap.',
    href: 'https://www.aresesylvester.com/',
    year: 2022,
    demo: 'https://drive.google.com/file/d/1DHGDV1PPAv0449WfFUwjy2BBQ3okfAQd/view?usp=drive_link',
    overview: 'Arese Sylvester is a Nigerian journalist.',
    description: 'This is her personal website.',
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'Apple',
    src: 'apple',
    slug: 'apple',
    code: 'apple',
    tech: 'NextJs, Tailwind, React-Responsive-Carousel, Framer-Motion.',
    href: 'https://joshuaedo-apple.vercel.app/',
    year: 2023,
    demo: 'https://twitter.com/thegr8joshua/status/1670077556521926656',
    overview: "Apple's landing page during the unveiling of the Vision Pro.",
    description: null,
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'Portfolio V3',
    src: 'portfolio-v3',
    slug: 'portfolio-v3',
    code: 'portfolio-v3',
    tech: 'NextJs, JQuery, NodeMailer, Tailwind, React-Bootstrap, Framer-Motion.',
    href: 'https://v3.joshuaedo.com/projects',
    year: 2023,
    demo: null,
    overview: 'My third portfolio website.',
    description:
      'Built while making the transition from create-react-app to NextJs.',
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'Netflix',
    src: 'netflix',
    slug: 'netflix',
    code: 'netflix',
    tech: 'ReactJs, TMDB API, Redux, React-Router, Firebase, Lodash',
    href: null,
    year: 2023,
    demo: 'https://youtu.be/krHx-I6npkM',
    overview: 'A movie trailer app.',
    description:
      'Complete with Firebase × Google user sign-in authentication, this website shows proficiency in Rest API integration along with skeletonized page loading for slow networks.',
    documentation: 'https://github.com/joshuaedo/netflix/#readme',
    isDisplayed: false,
  },
  {
    title: 'Cleander',
    src: 'cleander',
    slug: 'cleander',
    code: 'cleander',
    tech: 'HTML, CSS, Bootstrap, Font-Awesome',
    href: 'https://cleander.vercel.app/',
    year: 2022,
    demo: null,
    overview: 'Need a housekeeper?',
    description:
      'This is a landing page for a fictional website where users can hire housekeepers remotely. And yes Cleander is wordplay on cleaner and Tinder :}',
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'jQuerius',
    src: 'jquerius',
    slug: 'jquerius',
    code: 'jquerius',
    tech: 'NodeJs, ExpressJs, Render, Telegram API, Dotenv.',
    href: 'https://t.me/joshuaedo_bot',
    year: 2023,
    demo: null,
    overview: 'My Personal Telegram bot.',
    description:
      'Built while learning ExpressJs, jQuerius is capable of answering predefined questions about myself and as a bonus, it can tell my kinda joke.',
    documentation: null,
    isDisplayed: true,
  },
  {
    title: 'Style Your Div',
    src: 'style-your-div',
    slug: 'style-your-div',
    code: 'style-your-div',
    tech: 'HTML, CSS',
    href: 'https://style-your-div.vercel.app/',
    year: 2023,
    demo: 'https://twitter.com/thegr8joshua/status/1627770957971456001',
    overview: 'Edit text directly in the DOM to style the div.',
    description:
      'A CSS Playground that I personally think would be a great addition to W3schools.',
    documentation: 'https://github.com/joshuaedo/style-your-div#readme',
    isDisplayed: false,
  },
  {
    title: 'Ryter',
    src: 'ryter',
    slug: 'ryter',
    code: 'ryter',
    tech: 'HTML, Javascript, CSS, Font-Awesome.',
    href: 'https://ryter.vercel.app/',
    year: 2022,
    demo: null,
    overview: 'A productivity app for writers.',
    description:
      'From note-taking to speech-to-text functionality, this website is an amalgamation of 5 separate web apps that could prove useful to the average writer.',
    documentation: 'https://github.com/joshuaedo/ryter/#readme',
    isDisplayed: true,
  },
  {
    title: 'Business Card',
    src: 'business-card',
    slug: 'business-card',
    code: 'business-card',
    tech: 'ReactJs, Font-Awesome.',
    href: 'https://card.joshuaedo.com/',
    year: 2023,
    demo: null,
    overview: null,
    description:
      "Aptly named, it is a demo business card, built while I was in the process of understanding how to harness React's code-splitting features.",
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'Drum Kit',
    src: 'drum',
    slug: 'drum',
    code: 'Drum-Hero',
    tech: 'HTML, JavaScript, CSS.',
    href: 'https://joshuaedo-drum.vercel.app/',
    year: 2022,
    demo: null,
    overview: 'Click and play.',
    description:
      'A single page, 100vh webpage that allows users to play drum sounds by clicking buttons on the screen or some designated keys on the keyboard.',
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'Dice Game',
    src: 'dice',
    slug: 'dice',
    code: 'Dice-Game',
    tech: 'HTML, JavaScript, CSS.',
    href: 'https://joshuaedo-dice.vercel.app/',
    year: 2022,
    demo: null,
    overview:
      "If you're looking for a virtual coin toss then this should suffice.",
    description:
      "Using JavaScript's Math.random(), I ensured that with each refresh there's a new winner (or a draw in some cases).",
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'Portfolio V2',
    src: 'portfolio-v2',
    slug: 'portfolio-v2',
    code: 'portfolio-V2',
    tech: 'HTML, CSS',
    href: 'https://v2.joshuaedo.com/',
    year: 2022,
    demo: null,
    overview: 'My second portfolio website.',
    description:
      "Not a fancy landing page by today's standards but greatly improved from the first.",
    documentation: null,
    isDisplayed: false,
  },
  {
    title: 'Portfolio V1',
    src: 'portfolio-v1',
    slug: 'portfolio-v1',
    code: 'portfolio-V1',
    tech: 'HTML',
    href: 'https://v1.joshuaedo.com/',
    year: 2022,
    demo: null,
    overview: 'My first ever attempt at a portfolio website.',
    description: "A grounding reminder of how far I've come.",
    documentation: null,
    isDisplayed: false,
  },
];

const projects = allProjects
  .filter((project) => project.isDisplayed === true)
  .map((project, index, array) => {
    const nextIndex = (index + 1) % array.length;
    const nextProject = array[nextIndex];

    return {
      ...project,
      next: nextProject || array[0],
    };
  });

export { allProjects, projects };
