// tech: frameworks, api, semi-frameworks, stylers, animators
const projects = [
  {
    title: 'Sandra',
    src: 'sandra',
    slug: 'sandra',
    code: 'https://github.com/sandraokpara/blog',
    color: '#FFF',
    tech: 'Typescript, NextJs, Next-Auth, Hygraph, Sass, Tailwind, Framer-Motion, GSAP',
    href: 'https://sandraokpara.com',
    year: 2023,
    demo: null,
    overview: 'Writing on Earth.',
    description:
      "This blog is a canvas for Sandra Okpara's diverse range of interests.",
    documentation: 'https://github.com/sandraokpara/blog#readme',
    next: {
      title: 'Z',
      year: '2023',
      slug: 'z',
    },
  },
  {
    title: 'Z',
    src: 'z',
    slug: 'z',
    code: null,
    color: '#FFF',
    tech: 'Typescript, NextJs, Prisma, Next-Auth, React-Query, Upload-Thing, Tailwind',
    href: 'https://z.joshuaedo.com',
    year: 2023,
    demo: null,
    overview: 'Join the conversation.',
    description:
      'A community-oriented social network inspired by Reddit and Twitter.',
    documentation: null,
    next: {
      title: 'Galleria',
      year: '2023',
      slug: 'galleria',
    },
  },
  {
    title: 'Galleria',
    src: 'galleria',
    slug: 'galleria',
    code: 'galleria',
    color: '#8C8C8C',
    tech: 'Typescript, NextJs, Pexels API, Next-Auth, React-Query, DND-Kit, Tailwind',
    href: 'https://galleria.joshuaedo.com',
    year: 2023,
    demo: null,
    overview:
      'An interactive stock image gallery with drag-and-drop functionality.',
    description:
      'Galleria is my version of the HNGX 2023 Frontend Stage 3 Task.',
    documentation: null,
    next: {
      title: 'Spotify',
      src: 'spotify',
      slug: 'spotify',
    },
  },
  {
    title: 'Spotify',
    src: 'spotify',
    slug: 'spotify',
    code: 'spotify',
    color: '#FFF',
    tech: 'NextJs, Spotify API, Next-Auth, Recoil, Tailwind, Framer-Motion',
    href: 'https://joshuaedo-spotify.vercel.app/',
    year: 2023,
    demo: 'https://youtu.be/RDafUnvD090',
    overview:
      'A recreation of the Spotify web app UI with some conditional functionality.',
    description:
      'Apart from rendering songs and playlists, the app also acts as a remote control for other devices where you are logged into your Spotify Account.',
    documentation: 'https://github.com/joshuaedo/spotify#readme',
    next: {
      title: 'Prime',
      year: '2023',
      slug: 'prime',
    },
  },
  {
    title: 'Prime',
    src: 'prime',
    slug: 'prime',
    code: 'amazon',
    color: '#8C8C8C',
    tech: 'NextJs, Stripe, Firebase & Firestore, Redux, Tailwind',
    href: 'https://joshuaedo-prime.vercel.app/',
    year: 2023,
    demo: null,
    overview: 'An E-commerce app inspired by Amazon.com',
    description:
      'I used the Fake Store API to create an online store with full authentication and payment workflow.',
    documentation: null,
    next: {
      title: 'Blog',
      year: '2023',
      slug: 'blog',
    },
  },
  {
    title: 'Blog',
    src: 'blog',
    slug: 'blog',
    code: 'my-blog',
    color: '#8C8C8C',
    tech: 'NextJs, GraphQL, Hygraph, OpenAI Model Playground.',
    href: 'https://blog.joshuaedo.com/',
    year: 2023,
    demo: null,
    overview:
      'This app was built to gain experience in the utilization of GraphQL and Headless CMS.',
    description: 'Disclaimer: The articles on this website are AI-generated.',
    documentation: null,
    next: {
      title: 'Google',
      year: '2023',
      slug: 'google',
    },
  },
  {
    title: 'Google',
    src: 'google',
    slug: 'google',
    code: 'google',
    color: '#706D63',
    tech: 'NextJs, Google API, Recoil, Tailwind, Hero Icons.',
    href: 'https://joshuaedo-google.vercel.app/',
    year: 2023,
    demo: 'https://youtu.be/qO7OML8_Pnk',
    overview: "It's basically google.com but not quite.",
    description:
      "Utilizing the open source Google API, I recreated Google Search. To the casual user it's not immediately differentiable from the real website.",
    documentation: 'https://github.com/joshuaedo/google/#readme',
    next: {
      title: 'Apple',
      year: '2023',
      slug: 'apple',
    },
  },
  {
    title: 'Apple',
    src: 'apple',
    slug: 'apple',
    code: 'apple',
    color: '#FFF',
    tech: 'NextJs, Tailwind, React-Responsive-Carousel, Framer-Motion.',
    href: 'https://joshuaedo-apple.vercel.app/',
    year: 2023,
    demo: 'https://twitter.com/thegr8joshua/status/1670077556521926656',
    overview: "Apple's landing page during the unveiling of the Vision Pro.",
    description: null,
    documentation: null,
    next: {
      title: 'Portfolio V3',
      year: '2023',
      slug: 'portfolio-v3',
    },
  },
  {
    title: 'Portfolio V3',
    src: 'portfolio-v3',
    slug: 'portfolio-v3',
    code: 'portfolio-v3',
    color: '#8C8C8C',
    tech: 'NextJs, JQuery, NodeMailer, Tailwind, React-Bootstrap, Framer-Motion.',
    href: 'https://v3.joshuaedo.com/projects',
    year: 2023,
    demo: null,
    overview: 'My third portfolio website.',
    description:
      'Built while making the transition from create-react-app to NextJs.',
    documentation: null,
    next: {
      title: 'joshua-GPT',
      year: '2023',
      slug: 'joshua-gpt',
    },
  },
  {
    title: 'joshua-GPT',
    src: 'joshuaGPT',
    slug: 'joshua-gpt',
    code: null,
    color: '#8C8C8C',
    tech: 'NodeJs, ExpressJs, OpenAI API, Telegram API, Dotenv.',
    href: 'https://t.me/joshuaedo_bot',
    year: 2023,
    demo: 'https://youtu.be/yuroCFONrTo',
    overview: 'A multipurpose Telegram bot.',
    description:
      'Not only can it answer predefined questions about myself, this bot is also connected to the Open AI API, allowing it to function similarly to chatGPT.',
    documentation: null,
    next: {
      title: 'Ryter',
      year: '2022',
      slug: 'ryter',
    },
  },
  {
    title: 'Ryter',
    src: 'ryter',
    slug: 'ryter',
    code: 'ryter',
    color: '#EFE8D3',
    tech: 'HTML, Javascript, CSS, Font-Awesome.',
    href: 'https://ryter.vercel.app/',
    year: 2022,
    demo: null,
    overview: 'A productivity app for writers.',
    description:
      'From note-taking to speech-to-text functionality, this website is an amalgamation of 5 separate web apps that could prove useful to the average writer.',
    documentation: 'https://github.com/joshuaedo/ryter/#readme',
    next: null,
  },
];

export { projects };
